import React, { Component } from 'react'
import '../components/css/privacy.css'

class Privacy extends Component {
    render() {
        return (
            <div className="body">
                <h1 className="privacy-header">RoyalTrip Terms of Use for Riders</h1>
                <div className="group">
                    <div className="">RoyalTrip is an indigenous private limited company registered under PART A of the Companies and Allied Matters Act 2020, with registration number: RC 1717412, and founded in the Federal Republic of Nigeria. We are the holders of the RoyalTrip App franchise in Nigeria and the operation of the transportation app is carried out through RoyalTrip Hailing & Advertising Agency Limited. RoyalTrip is a mobile App for making transportation orders. It transmits transportation service requests to the transportation service providers who have been registered as users of the RoyalTrip Hailing System.<br></br> The following are our terms of use as a rider on the RoyalTrip system:</div>
                </div>
                <div className="group">
                    <h1 className="">A. Using the RoyalTrip App</h1>
                    <div className="">i. The use of the RoyalTrip app requires installation of the software and registration of a user account. During the installation of the RoyalTrip app, the mobile number of the RoyalTrip service user is linked to the respective user account and added to the database. <br></br> ii. When using the RoyalTrip App, the user can choose whether he/she wishes to pay in cash or via in-App payment for the transportation service 
to the driver. Once a payment option has been selected, the user cannot change this. <br></br> iii. Any complaints can be sent to our support team via email support@royaltrips.com.ng, or by calling our 24/7 support line 01-3438076, +234- (0) 702-5004-829.
                </div>
                </div>
                <div className="group">
                    <h1 className="">B. In-App Payment Conditions</h1>
                    <div className="">i. In-App payments can be made by a user of the RoyalTrip App who has added his/her debit card on the app. <br></br> ii. When making in-App payments, the receiver of the payment is RoyalTrip Hailing & Advertising Agency Limited, who forwards the Drivers/Fleet Partners commission to their bank accounts. <br></br> iii. When making in-App payments, a service fee is added per each order of transportation service. The named service fee includes payment commission fees, incl. Visa / MasterCard service fees. The amount of the service fee is displayed in the mobile app. In the event that the in-App payment intermediary enacts a fee for the usage of the payment service, which has to be paid by the customers separately, then the named fees are not included in the RoyalTrip in-App payment item. <br></br> iv. The intermediation of card payments in the RoyalTrip app is carried out through Paystack  pursuant to the following Terms & Conditions: https://paystack.com/terms <br></br> v. RoyalTrip shall be responsible for the functioning of card payments and offers card owners support in solving problems. The resolution of in-App payment related disputes also takes place through RoyalTrip in cases where the issue is directly related to the in-app payment process. The contact for RoyalTrip in-App payment support service is support@royaltrips.com.ng – Inquiries submitted by e-mail shall receive a response within 5 working days. RoyalTrip shall resolve all in-App payment related complaints and applications upon complete clarity on the issue within four business days. <br></br> vi. When offering in-App payments, RoyalTrip acts as the economic agent of transportation service providers by intermediating payments made in the RoyalTrip app. The obligation of the customer in front of the transportation service provider shall be considered fulfilled as of the moment when the payment order is made for the payment of funds into the RoyalTrip bank account. RoyalTrip shall not be responsible for the exercise of the customer's payment order.
                    </div>
                </div>
                <div className="group">
                    <h1 className="">C. Ordering or Cancelling a Transportation Service</h1>
                    <div className="">i. If the RoyalTrip app user orders a vehicle and the driver has confirmed the receipt of service, then the transportation is considered pre-ordered. <br></br> ii. Cancelling the use of an ordered transportation is considered to be the situation where the driver has been notified about the receipt of an order and the RoyalTrip app user waives the use of the transportation service after a notice has been received. <br></br> iii. Cancelling the use of an ordered transportation is also considered to be the situation where the user of the RoyalTrip app or people whom the transportation was ordered for do not appear in the vehicle within 5 minutes as of the time when the driver notified them about the arrival of the vehicle in its destination. <br></br> iv. In case of cancelling the transportation service the RoyalTrip app user is required to pay 500 Naira as a penalty fee. In the event that the RoyalTrip user notifies about the cancelling of transportation service within 5 minutes as of receiving of the notification concerning the receipt of the order through RoyalTrip, the user does not have to pay the penalty fee. <br></br> v. We have the right to revoke the right to use the app if the user has waived the use of transportation service on 3 successive instances in one 24 hour period. In that case the app notifies the user about the number of cancellations and after waiving the 3rd time, RoyalTrip cancels the usage right. RoyalTrip usage right can be cancelled for up to 24 hours. After that, the user can reactivate his/her user account by contacting the local team via email. Access to App can also be revoked on the basis of harassment, providing false information/allegations and engaging in any criminal activities.
                    </div>
                </div>
                <div className="group">
                    <h1 className="">D. Legal Implications for Using the RoyalTrip App</h1>
                    <div className="">i. RoyalTrip is a mobile app that enables persons requiring a transportation service to find a suitable provider closest to them. <br></br> ii. The use of the RoyalTrip App is based on a non-exclusive license issued by RoyalTrip Hailing & Advertising Agency Limited. The license agreement is valid for a non-limited period and is free of charge for the customer. In case of any faults in the software, we shall endeavor to correct them as soon as possible, but please keep in mind that the functionality of the App may be restricted due to occasional technical errors and we are not able to guarantee unlimited faultless functioning of the App at all times. We shall also accept no liability for any losses incurred as a consequence of the RoyalTrip App not functioning or not being usable in the desired manner. In the event that the customer's right to use the app is cancelled, the corresponding non-exclusive license shall also be repealed. <br></br> iii. As the RoyalTrip App is primarily a link between customers and transportation service providers, RoyalTrip cannot influence or take any responsibility for the quality or defects of the service. Driver-partners are not employees and for this reason, we are unable to guarantee consistently accurate and faultless provision of transportation services located via RoyalTrip. For resolving complaints, please contact our support team (referred to in clause 1.3). <br></br> iv. The RoyalTrip App does not constitute an offer or brokerage of transportation for customers. The RoyalTrip App is not a means for organizing the provision of transportation services. It is also not an agency service for finding customers for transportation providers. <br></br> v. The consumer's right of refund (withdrawal) is not applied to RoyalTrip App orders. <br></br> vi. A rider must be 18 and above to register and ride. If a rider in under the age of 18, he or she must be accompanied by someone who is 18 years or older. Unaccompanied minors are not to be in rides and RoyalTrip bears no liability for unaccompanied minors. <br></br> vii. The RoyalTrip App is set up to help people move from point A to B and is not a means for the delivery of parcels. Moving parcels is not under the purview of this platform and RoyalTrip shall not be held liable for missing or undelivered parcels. A rider must also be accountable for their items during a ride. <br></br> viii. RoyalTrip would help to recover lost and forgotten items only in the event that these items are found by the driver-partner and taken to the Bolt office. Furthermore, these recovered items that have been taken to the RoyalTrip office have a 14-day time span to be retrieved after which RoyalTrip will not be held liable for them.
                    </div>
                </div>
                <div className="group">
                    <h1 className="">E. Conditions a Customer Must Accept for Registering an account with RoyalTrip</h1>
                    <div className="">i. RoyalTrip shall have the right to add the personal data of the app user to the RoyalTrip database and to forward the personal data to transportation service providers in accordance with RoyalTrip’s Privacy Policy (https://www.royaltrips.com.ng/privacy/). <br></br> ii. RoyalTrip shall have a right to make unilateral amendments to the Terms and Conditions and Privacy Policy and to relinquish the database to third parties. We may notify users of changes to Terms and Conditions and Privacy Policy. <br></br> iii. RoyalTrip shall be entitled to transfer the database of personal data to third parties without prior notification of the app users. In case of a transfer of the business or the database, the rights and conditions arising from this license agreement shall be transferred as well. <br></br> iv. RoyalTrip shall be entitled to forward personal data and bank data to debit card and mobile payment intermediaries. <br></br> v. RoyalTrip has the right to send marketing messages and authentication codes through SMS messages. <br></br> vi. RoyalTrip only encourages the use of 2 modes of payments i.e. Cash payment and the in-App payment (Card). RoyalTrip bears no liability on damages that may occur outside the outlined acceptable payment methods.
                    </div>
                </div>
                <div className="group">
                    <h1 className="">F. What Constitutes Good Practice While Using the RoyalTrip App</h1>
                    <div className="">i. As RoyalTrip is not a provider or broker of the transportation service, we are unable to influence the quality of the transportation service. Any issues with defects or quality of the transportation service shall be resolved in accordance with the rules and regulations of the transportation service provider or the relevant supervisory authority.<br></br> ii. RoyalTrip is committed to contributing to improvement of the quality of transportation services. For this reason, we continuously collate ratings and ask to fill out a feedback form in the RoyalTrip App. This enables us to offer suggestions to the transportation service providers for improving the quality of their service. <br></br> iii. We expect that the users of the RoyalTrip App use the app in good faith and are respectful of the drivers who offer their services through RoyalTrip.<br></br> iv. RoyalTrip shall make every effort to ensure that only drivers, who have integrity and are respectful of their profession and customers, use the RoyalTrip App. However, we are in no position to guarantee that every provider of transportation services, located via the RoyalTrip App, satisfies the aforementioned criteria at all times. If you experience objectionable transportation service, please notify the company responsible for the service, a supervisory authority or our support team (See clause A(i) ).<br></br> v. In the event that we receive a complaint, which has an element of the commission of a crime by a transport service provider, the Customer shall make a formal complaint to the Nigeria Police Force, tender a report to RoyalTrip, and the transport service provider shall cooperate with the Nigeria Police Force in ensuring that the allegations contained in the complaint are diligently investigated. <br></br> vii. In the event that a user makes an allegation against a Driver-partner especially in events where details of partners are shared online,Driver-partners reserve the right to seek legal redress and may pursue legal recourse against damages to their character.
                    </div>
                </div>
                <div className="group">
                    <h1 className="">G. RoyalTrip Free Rides Referral System</h1>
                    <div className="">i. RoyalTrip shall reward riders with a discount code for every new unique rider they invite to use the app. Discount codes are applicable when card or cash payment option is selected. <br></br> ii. The discount code will be valid if the new rider uses cash payment or card payment for the first ride. <br></br> iii. RoyalTrip has the right to void any discount codes and block rider accounts if it suspects any fraudulent activities and charge the rider for the damages caused.    </div>
                </div>
            </div>
        )
    }
}

export default Privacy